label: Config Connector AlloyDBCluster
markdownDescription: Creates yaml for a AlloyDBCluster resource
insertText: |
  apiVersion: alloydb.cnrm.cloud.google.com/v1beta1
  kind: AlloyDBCluster
  metadata:
    name: \${1:alloydbcluster-name}
  spec:
    location: \${2:us-east1}
    networkConfig:
      networkRef:
        name: \${3:alloydbcluster-dep-regular}
    projectRef:
      external: \${4:[PROJECT_ID?]}
    automatedBackupPolicy:
      backupWindow: \${5:3600s}
      encryptionConfig:
        kmsKeyNameRef:
          name: \${6:alloydbcluster-dep-regular}
      enabled: \${7:true}
      labels:
        source: \${8:kcc}
      location: \${9:us-east1}
      timeBasedRetention:
        retentionPeriod: \${10:43200s}
      weeklySchedule:
        daysOfWeek:
        - \${11:MONDAY}
        startTimes:
        - hours: \${12:4}
          minutes: \${13:0}
          seconds: \${14:0}
          nanos: \${15:0}
    encryptionConfig:
      kmsKeyNameRef:
        name: \${16:alloydbcluster-dep-regular}
    initialUser:
      user: \${17:postgres}
      password:
        value: \${18:postgres}
