label: Config Connector EdgeContainerVpnConnection
markdownDescription: Creates yaml for a EdgeContainerVpnConnection resource
insertText: |
  apiVersion: edgecontainer.cnrm.cloud.google.com/v1beta1
  kind: EdgeContainerVpnConnection
  metadata:
    name: \${1:edgecontainervpnconnection-name}
  spec:
    projectRef:
      external: \${2:[PROJECT_ID?]}
    location: \${3:us-central1}
    clusterRef:
      name: \${4:edgecontainercluster-local-control-plane-dep}
    enable_high_availability: \${5:true}
