label: Config Connector EdgeContainerCluster
markdownDescription: Creates yaml for a EdgeContainerCluster resource
insertText: |
  apiVersion: edgecontainer.cnrm.cloud.google.com/v1beta1
  kind: EdgeContainerCluster
  metadata:
    labels:
      \${1:label-one}: \${2:value-one}
    name: \${3:edgecontainercluster-name}
  spec:
    projectRef:
      external: \${4:[PROJECT_ID?]}
    location: \${5:us-central1}
    networking:
      clusterIpv4CidrBlocks:
      - \${6:10.0.0.0/16}
      servicesIpv4CidrBlocks:
      - \${7:10.1.0.0/16}
    fleet:
      projectRef:
        external: \${8:projects/[PROJECT_NUMBER?]}
    authorization:
      adminUsers:
        usernameRef:
          external: \${9:[CLUSTER_ADMIN_ACCOUNT?]}
    maintenancePolicy:
      window:
        recurringWindow:
          window:
            startTime: \${10:2023-01-01T08:00:00Z}
            endTime: \${11:2023-01-01T17:00:00Z}
          recurrence: \${12:FREQ=WEEKLY;BYDAY=SA}
