label: Config Connector EdgeContainerNodePool
markdownDescription: Creates yaml for a EdgeContainerNodePool resource
insertText: |
  apiVersion: edgecontainer.cnrm.cloud.google.com/v1beta1
  kind: EdgeContainerNodePool
  metadata:
    name: \${1:edgecontainernodepool-name}
  spec:
    projectRef:
      external: \${2:[PROJECT_ID?]}
    location: \${3:us-central1}
    clusterRef:
      name: \${4:edgecontainercluster-remote-control-plane-dep}
    nodeLocation: \${5:[NODE_LOCATION?]}
    nodeCount: \${6:1}
